services:
  jenkins-controller:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab05-net

  ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile.ssh_agent
    container_name: ssh-agent
    networks:
      - lab05-net

  ansible-agent:
    build:
      context: .
      dockerfile: Dockerfile.ansible_agent
    container_name: ansible-agent
    networks:
      - lab05-net

  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test_server
    container_name: test-server
    ports:
      - "8081:80"
    networks:
      - lab05-net

networks:
  lab05-net:
    driver: bridge

volumes:
  jenkins_home:
