FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y openssh-server openjdk-17-jdk git php-cli php-mbstring php-xml unzip curl && rm -rf /var/lib/apt/lists/*
RUN useradd -m -d /home/jenkins -s /bin/bash jenkins && echo "jenkins:jenkins" | chpasswd
RUN mkdir -p /home/jenkins/.ssh && chmod 700 /home/jenkins/.ssh
COPY keys/jenkins_agent.pub /home/jenkins/.ssh/authorized_keys
RUN chmod 600 /home/jenkins/.ssh/authorized_keys && chown -R jenkins:jenkins /home/jenkins/.ssh
RUN mkdir /var/run/sshd
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
